version: '3'
services:
  bot:
    image: kukks/btcpayserverslackbot
    restart: unless-stopped
    build: ./BtcPayServerSlackBot
    volumes:
      - "./data:/app/data:rw"
    environment:
      - SlackApiKey
      - HelpEnabled
      - StatsEnabled
      - AboutEnabled